name: eos-s3
channels:
  - conda-forge
  - litex-hub
dependencies:
  - litex-hub::yosys=0.15_51_g6318db615=20220317_162926_py37
  - litex-hub::symbiflow-yosys-plugins=1.0.0_7_832_ga2a80a1=20220317_162926
  - litex-hub::vtr-optimized=8.0.0_5338_g829c06d8f=20220409_131122
  - make
  - lxml
  - simplejson
  - intervaltree
  - git
  - pip
  # Packages installed from PyPI
  - pip:
    - -r requirements.txt
