name: doc-test

on:
 push:
 pull_request:
 schedule:
  - cron: "0 0 * * *"

jobs:


  Matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}

    steps:

      - name: Generate examples matrix
        id: generate
        shell: python
        run: |
          examples = [
              "counter",
              "picosoc",
              "litex",
              "litex_linux",
              "button_controller",
              "pulse_width_led",
              "timer",
              "hello-a"
          ]
          osvers = [
              ("ubuntu", "xenial"),
              ("ubuntu", "bionic"),
              ("ubuntu", "focal"),
              ("centos", "7"),
              ("centos", "8"),
              ("debian", "buster"),
              ("debian", "bullseye"),
              ("debian", "sid")
          ]
          jobs = []
          for osver in osvers:
              jobs += [{
                  'fpga-fam': "xc7",
                  'os': osver[0],
                  'os-version': osver[1],
                  'example': example
              } for example in examples]

          jobs += [{
              'fpga-fam': "eos-s3",
              'os': osver[0],
              'os-version': osver[1],
              'example': "counter"
          } for osver in osvers]

          print('::set-output name=matrix::' + str(jobs))


  Test:
    needs: Matrix
    runs-on: [self-hosted, Linux, X64]
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.Matrix.outputs.matrix) }}

    env:
      LANG: "en_US.UTF-8"
      DEBIAN_FRONTEND: "noninteractive"

    container: ${{matrix.os}}:${{matrix.os-version}}

    steps:
      - name: Setup repository
        uses: actions/checkout@v2

      - name: Install utils
        if: ${{matrix.os == 'ubuntu' || matrix.os == 'debian'}}
        run: apt -qqy update && apt -qqy install wget locales && locale-gen $LANG

      - name: Install utils
        if: ${{matrix.os == 'centos'}}
        run: yum -y install wget

      - name: Install tuttest
        run: |
          wget https://github.com/antmicro/tuttest/releases/download/v0.2-beta/tuttest -O /usr/bin/tuttest
          chmod a+rx /usr/bin/tuttest

      - name: Install SymbiFlow toolchain
        run: bash .github/scripts/install-toolchain.sh ${{matrix.fpga-fam}} ${{matrix.os}}

      - name: Build examples
        run: bash .github/scripts/build-examples.sh ${{matrix.fpga-fam}} ${{matrix.example}}

      - uses: actions/upload-artifact@v2
        with:
          name: symbiflow-examples-bitstreams
          path: |
            **/*.bit
            **/plot_*.svg
